"""add org_storage_snapshot

Revision ID: 4af2ecb15ad0
Revises: 598bc2e555d4
Create Date: 2026-05-26 10:34:52.081732

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4af2ecb15ad0"
down_revision: Union[str, Sequence[str], None] = "598bc2e555d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "org_storage_snapshot",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("team_id", sa.String(), nullable=False),
        sa.Column("total_bytes", sa.BigInteger(), nullable=False),
        sa.Column("breakdown_json", sa.String(), nullable=True),
        sa.Column("per_user_json", sa.String(), nullable=True),
        sa.Column("scanned_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_org_storage_snapshot_team_scanned", "org_storage_snapshot", ["team_id", "scanned_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_org_storage_snapshot_team_scanned", table_name="org_storage_snapshot")
    op.drop_table("org_storage_snapshot")
    # ### end Alembic commands ###
