"""check oauth changes

Revision ID: 7eb412acff0c
Revises: c175b784119c
Create Date: 2025-12-04 16:28:22.984188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eb412acff0c'
down_revision: Union[str, Sequence[str], None] = 'c175b784119c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth_account', 'user_id',
               existing_type=sa.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('oauth_account', 'access_token',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.alter_column('oauth_account', 'account_email',
               existing_type=sa.VARCHAR(length=320),
               nullable=False)
    op.drop_index(op.f('ix_oauth_account_oauth_name_account_id'), table_name='oauth_account')
    op.create_index(op.f('ix_oauth_account_account_id'), 'oauth_account', ['account_id'], unique=False)
    op.create_index(op.f('ix_oauth_account_oauth_name'), 'oauth_account', ['oauth_name'], unique=False)
    op.drop_column('oauth_account', 'account_id_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_account', sa.Column('account_id_token', sa.VARCHAR(length=1024), nullable=True))
    op.drop_index(op.f('ix_oauth_account_oauth_name'), table_name='oauth_account')
    op.drop_index(op.f('ix_oauth_account_account_id'), table_name='oauth_account')
    op.create_index(op.f('ix_oauth_account_oauth_name_account_id'), 'oauth_account', ['oauth_name', 'account_id'], unique=1)
    op.alter_column('oauth_account', 'account_email',
               existing_type=sa.VARCHAR(length=320),
               nullable=True)
    op.alter_column('oauth_account', 'access_token',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('oauth_account', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
