"""create_quota_tables

Revision ID: 90042b8ff500
Revises: f278bbaa6f67
Create Date: 2025-12-23 10:18:54.861166

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "90042b8ff500"
down_revision: Union[str, Sequence[str], None] = "f278bbaa6f67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quota_holds",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("team_id", sa.String(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=True),
        sa.Column("minutes_requested", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("released_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_quota_holds_job_id", "quota_holds", ["job_id"], unique=False)
    op.create_index("idx_quota_holds_task_id", "quota_holds", ["task_id"], unique=False)
    op.create_index("idx_quota_holds_user_team_status", "quota_holds", ["user_id", "team_id", "status"], unique=False)
    op.create_table(
        "quota_usage",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("team_id", sa.String(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("experiment_id", sa.String(), nullable=False),
        sa.Column("minutes_used", sa.Float(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_quota_usage_job_id", "quota_usage", ["job_id"], unique=False)
    op.create_index(
        "idx_quota_usage_user_team_period", "quota_usage", ["user_id", "team_id", "period_start"], unique=False
    )
    op.create_table(
        "team_quotas",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("team_id", sa.String(), nullable=False),
        sa.Column("monthly_quota_minutes", sa.Integer(), nullable=False),
        sa.Column("current_period_start", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id"),
    )
    op.create_table(
        "user_quota_overrides",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("team_id", sa.String(), nullable=False),
        sa.Column("monthly_quota_minutes", sa.Integer(), nullable=False),
        sa.Column("current_period_start", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_user_quota_overrides_user_team", "user_quota_overrides", ["user_id", "team_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_quota_overrides_user_team", table_name="user_quota_overrides")
    op.drop_table("user_quota_overrides")
    op.drop_table("team_quotas")
    op.drop_index("idx_quota_usage_user_team_period", table_name="quota_usage")
    op.drop_index("idx_quota_usage_job_id", table_name="quota_usage")
    op.drop_table("quota_usage")
    op.drop_index("idx_quota_holds_user_team_status", table_name="quota_holds")
    op.drop_index("idx_quota_holds_task_id", table_name="quota_holds")
    op.drop_index("idx_quota_holds_job_id", table_name="quota_holds")
    op.drop_table("quota_holds")
    # ### end Alembic commands ###Okay
