services:
  transformerlab-test:
    build:
      context: .
      dockerfile: test/docker/Dockerfile
    environment:
      - TLAB_USE_LOCAL_GALLERIES=1
      - TFL_STORAGE_PROVIDER=localfs
      - TFL_STORAGE_URI=/root/tlab_local_workspace
    ports:
      - '8338:8338'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8338']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
