name: unsloth-text-to-speech-train-task
github_repo_url: https://github.com/transformerlab/transformerlab-app
github_repo_dir: api/transformerlab/galleries/examples/unsloth-text-to-speech-train
resources:
  accelerators: "RTX3090:1"
setup: uv pip install torch unsloth transformers==4.52.3 snac transformerlab "datasets==3.6.0" librosa soundfile "torch==2.10.0"
run: "python unsloth-text-to-speech-train/train.py"
envs:
  WANDB_PROJECT: "unsloth-text-to-speech-training"
  PYTHONUNBUFFERED: "1"
  HF_TOKEN: "{{secret._HF_TOKEN}}"
  WANDB_API_KEY: "{{secret._WANDB_API_KEY}}"
parameters:
  model_name: {"type": "enum", "default": "unsloth/orpheus-3b-0.1-ft", "options": ["unsloth/orpheus-3b-0.1-ft", "unsloth/csm-1b"], "ui_widget": "radio", "title": "Model Name"}
  dataset: "bosonai/EmergentTTS-Eval"
  audio_column_name: "audio"
  text_column_name: "text_to_synthesize"
  lora_alpha: 32
  lora_dropout: 0.0
  lora_r: 16
  maximum_sequence_length: 1024
  max_grad_norm: 0.3
  learning_rate: 0.00005
  learning_rate_schedule: "linear"
  batch_size: 1
  num_train_epochs: 1
  weight_decay: 0.0
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 0.00000001
  sampling_rate: 24000
  max_steps: -1
  "model_architecture": {
      "type": "enum",
      "default": "OrpheusForConditionalGeneration",
      "options": ["OrpheusForConditionalGeneration", "CsmForConditionalGeneration"],
      "ui_widget": "radio",
      "title": "Model Architecture"
    }
