[build]
  command = "npm run build"
  publish = "build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- ."

[build.environment]
  NODE_VERSION = "18"

# Optional: Configure build hooks that can receive parameters
[template.environment]
  APP_VERSION = "Set automatically by build hook"


[[redirects]]
  from = "https://transformerlab.ai/install.sh"
  to = "https://github.com/transformerlab/transformerlab-app/releases/latest/download/install.sh"
  status = 302
  force = true

[[redirects]]
  from = "https://lab.cloud/install.sh"
  to = "https://github.com/transformerlab/transformerlab-app/releases/latest/download/install.sh"
  status = 302
  force = true

[[redirects]]
  from = "https://transformerlab.ai/*"
  to = "https://lab.cloud/:splat"
  status = 301
  force = true