"""Locate the Nebius CLI for subprocess use (same venv as the API process)."""

from __future__ import annotations

import hashlib
import os
import shutil
import sys
import tempfile
from importlib.metadata import entry_points
from pathlib import Path
from typing import List


def _known_nebius_locations() -> List[Path]:
    home = Path.home()
    return [
        home / ".nebius" / "bin" / "nebius",
        home / ".local" / "bin" / "nebius",
    ]


def _nebius_console_script_registered() -> bool:
    """True if the installed nebius distribution exposes a `nebius` console script."""
    try:
        return bool(tuple(entry_points().select(group="console_scripts", name="nebius")))
    except ValueError:
        return False


def _entrypoint_wrapper_script() -> Path:
    """Small executable script that runs the setuptools console_scripts entry (no `python -m nebius`)."""
    key = hashlib.sha256(str(Path(sys.executable).resolve()).encode()).hexdigest()[:16]
    path = Path(tempfile.gettempdir()) / f"transformerlab-nebius-cli-{key}.py"
    shebang = f"#!{sys.executable}\n"
    body = """# Generated by Transformer Lab — runs Nebius setuptools console_scripts entry.
import sys
from importlib.metadata import entry_points

if __name__ == "__main__":
    eps = list(entry_points().select(group="console_scripts", name="nebius"))
    if not eps:
        print(
            "Nebius is installed but no console_scripts entry named 'nebius' was found.",
            file=sys.stderr,
        )
        sys.exit(2)
    sys.exit(eps[0].load()())
"""
    content = shebang + body
    if not path.is_file() or path.read_text(encoding="utf-8") != content:
        path.write_text(content, encoding="utf-8")
        os.chmod(path, 0o700)
    return path


def nebius_cli_argv_prefix() -> List[str]:
    """Return argv prefix to invoke Nebius (venv binary, PATH, or entry-point wrapper)."""
    bin_dir = Path(sys.executable).resolve().parent
    for name in ("nebius", "nebius.exe"):
        candidate = bin_dir / name
        if candidate.is_file():
            return [str(candidate)]
    for candidate in _known_nebius_locations():
        if candidate.is_file():
            return [str(candidate)]
    resolved = shutil.which("nebius")
    if resolved:
        return [resolved]
    if _nebius_console_script_registered():
        return [str(_entrypoint_wrapper_script())]
    raise RuntimeError(
        "Nebius CLI could not be resolved: no venv script, no PATH binary, and no console_scripts "
        "entry named 'nebius'. Install the `nebius` package in this environment."
    )


def nebius_cli_available() -> bool:
    """True if we can invoke Nebius (venv binary, PATH, or setuptools console_scripts)."""
    bin_dir = Path(sys.executable).resolve().parent
    for name in ("nebius", "nebius.exe"):
        if (bin_dir / name).is_file():
            return True
    for candidate in _known_nebius_locations():
        if candidate.is_file():
            return True
    if shutil.which("nebius"):
        return True
    return _nebius_console_script_registered()
