name: Publish

on:
  push:
    branches:
      - 'add/cloudzip'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install and build
        run: |
          npm install
          npm run postinstall
          npm run build

      - name: Zip static web assets
        run: |
          zip -r transformerlab-web.zip release/cloud/

      - name: Create draft GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.13.0-test
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload static assets to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.13.0-test
          files: transformerlab-web.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

